// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/v1.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/keyBlock.tsx";
import * as $$1 from "./islands/keyBlockDash.tsx";
import * as $$2 from "./islands/knob-block.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/v1.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/keyBlock.tsx": $$0,
    "./islands/keyBlockDash.tsx": $$1,
    "./islands/knob-block.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
